services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Extcode\CartEvents\:
    resource: '../Classes/*'

  Extcode\CartEvents\EventListener\Order\Stock\HandleStock:
    tags:
      - name: event.listener
        identifier: 'cart-events--order--stock--handle-stock'
        event: Extcode\Cart\Event\Order\StockEvent

  Extcode\CartEvents\EventListener\Order\Stock\FlushCache:
    tags:
      - name: event.listener
        identifier: 'cart-events--order--stock--flush-cache'
        event: Extcode\Cart\Event\Order\StockEvent
        after: 'cart-events--order--stock--handle-stock'

  Extcode\CartEvents\EventListener\RetrieveProductsFromRequest:
    tags:
      - name: event.listener
        identifier: 'cart-events--retrieve-products-from-request'
        event: Extcode\Cart\Event\RetrieveProductsFromRequestEvent

  Extcode\CartEvents\EventListener\CheckProductAvailability:
    tags:
      - name: event.listener
        identifier: 'cart-events--check-product-availability'
        event: Extcode\Cart\Event\CheckProductAvailabilityEvent

  Extcode\CartEvents\Updates\SlugUpdater:
    public: true
