# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2018-2021
  project: Cart Events
  version: 2.1
  release: 2.1.6